// Shared product catalog. Used by home, /products, and category landing pages.
export const products = [
  {
    id: 1,
    name: 'Premium Cargo Pants',
    category: 'Cargo Pants',
    categorySlug: 'cargo-pants-manufacturer',
    article: '10086',
    fabric: 'Nylon Crush Lycra Terry',
    gsm: 260,
    price: 450,
    image: '/images/art-201.jpeg',
    colors: ['Black', 'Grey', 'Khaki', 'Olive'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    useCase: 'Ideal for streetwear, travel and casual daily wear where utility pockets matter.',
    care: 'Machine wash cold, inside out. Do not bleach. Tumble dry low. Warm iron if needed.',
    description:
      'A structured cargo built on nylon crush lycra terry for stretch recovery and a dry hand-feel. Bar-tacked pockets, tapered leg and a ribbed hem. Supplied bulk with custom colours, drawcords and branding.',
  },
  {
    id: 2,
    name: 'Casual Jogger Pants',
    category: 'Casual Pants',
    categorySlug: 'joggers-manufacturer',
    article: '10075',
    fabric: 'Bubble Crush',
    gsm: 240,
    price: 420,
    image: '/images/artical-205.jpeg',
    colors: ['Grey', 'Green', 'Black', 'Brown'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    useCase: 'Ideal for gym, athleisure and casual wear with an elasticated, move-friendly fit.',
    care: 'Machine wash cold with like colours. Do not bleach. Line dry or tumble dry low. Cool iron.',
    description:
      'A lightweight bubble-crush jogger with an elastic waist, drawcord and cuffed ankle. Breathable, quick-drying and shape-retaining across wash cycles. Available bulk with custom labelling and packing.',
  },
  {
    id: 3,
    name: 'Cotton Twill Cargo',
    category: 'Cargo Pants',
    categorySlug: 'cargo-pants-manufacturer',
    article: '10046',
    fabric: 'Cotton Twill',
    gsm: 300,
    price: 380,
    image: '/images/art4.jpeg',
    colors: ['Khaki', 'Camel', 'Brown', 'Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    useCase: 'Ideal for workwear, outdoor and rugged casual use that needs a firm, durable fabric.',
    care: 'Machine wash warm. Do not bleach. Tumble dry medium. Medium-hot iron. Expect slight first-wash shrinkage.',
    description:
      'A heavier woven cotton twill cargo with reinforced seams and deep bellow pockets. Holds structure, softens with wear and takes screen print or embroidery cleanly. Bulk MOQ 10 with volume pricing.',
  },
  {
    id: 4,
    name: 'Nylon Cargo Joggers',
    category: 'Casual Pants',
    categorySlug: 'joggers-manufacturer',
    article: '10005',
    fabric: 'Nylon Crush',
    gsm: 220,
    price: 400,
    image: '/images/art-202.jpeg',
    colors: ['Grey', 'Khaki', 'Black', 'Brown'],
    sizes: ['M', 'L', 'XL'],
    useCase: 'Ideal for casual and light-active wear — a cargo-jogger hybrid with a relaxed taper.',
    care: 'Machine wash cold, inside out. Do not bleach or wring. Tumble dry low. Cool iron only.',
    description:
      'Nylon crush jogger with cargo pockets, elastic waist and ribbed cuffs. Crinkle texture hides creasing and travels well. Supplied bulk with bespoke colour and trim options.',
  },
  {
    id: 5,
    name: 'Premium Nylon Pant',
    category: 'Casual Pants',
    categorySlug: 'track-pants-manufacturer',
    article: '10004',
    fabric: 'Nylon Crush',
    gsm: 230,
    price: 440,
    image: '/images/art-203.jpeg',
    colors: ['Black', 'Grey', 'Brown', 'Olive', 'Camel', 'Sky'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
    useCase: 'Ideal for track, travel and everyday casual wear with a clean, slim silhouette.',
    care: 'Machine wash cold. Do not bleach. Hang or tumble dry low. Cool iron if required.',
    description:
      'A clean-lined nylon crush pant with a side-seam pocket, zip option and an elastic or fixed waistband. Offered in a six-colour base range and extended sizing to 3XL. Bulk with custom branding.',
  },
  {
    id: 6,
    name: 'Heavy Lycra Collection',
    category: 'Heavy Lycra',
    categorySlug: 'track-pants-manufacturer',
    article: '10000',
    fabric: 'Heavy Lycra',
    gsm: 320,
    price: 550,
    image: '/images/artical-6.png',
    colors: ['Black', 'Grey'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    useCase: 'Ideal for formal-casual and office wear needing a heavier, structured stretch fabric.',
    care: 'Machine wash cold, gentle cycle. Do not bleach. Do not tumble dry — hang to dry. Warm iron.',
    description:
      'A heavyweight lycra-blend trouser with four-way stretch, crease resistance and a tailored fall. Waist-sized 30–44 for precise fitting. Bulk MOQ 10 with custom hemming and labelling.',
  },
];

export const categories = [
  {
    slug: 'track-pants-manufacturer',
    label: 'Track Pants',
    h1: 'Track Pants Manufacturer',
  },
  {
    slug: 'joggers-manufacturer',
    label: 'Joggers',
    h1: 'Joggers Manufacturer',
  },
  {
    slug: 'cargo-pants-manufacturer',
    label: 'Cargo Pants',
    h1: 'Cargo Pants Manufacturer',
  },
  {
    slug: 'custom-teamwear',
    label: 'Custom Teamwear',
    h1: 'Custom Teamwear Manufacturer',
  },
];
